import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import PrivyAppProvider from "@/providers/privy-provider";
import { Toaster } from 'sonner'
import WalletProvider from "@/providers/wallet-provider";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bricolageGrotesque.variable}`}>
      <body>
        <PrivyAppProvider>
          <WalletProvider>
            {children}
            </WalletProvider>
          </PrivyAppProvider>
        <Toaster />
      </body>
    </html>
  );
}
