name: Data Collector

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          collector-node/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('collector-node/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
          
    - name: Build collector
      working-directory: ./collector-node
      run: |
        echo "Building collector-node..."
        cargo build --release
        
    - name: Run collector
      working-directory: ./collector-node
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        RUST_LOG: info
      run: |
        echo "Starting data collection..."
        ./target/release/collector-node
        echo "Data collection completed successfully"
      timeout-minutes: 50